CC=clang
OPTIONS=-c
SOURCES=tracker.c tracker-test.c
OBJS=$(SOURCES:.c=.o)
EXE=Tracker

all:
	$(CC) $(OPTIONS) $(SOURCES)
	$(CC) -pthread $(OBJS) -o $(EXE)

debug:
	$(CC) $(OPTIONS) -g -DDEBUG $(SOURCES)
	$(CC) -pthread $(OBJS) -o $(EXE)

clean:
	rm $(OBJS) $(EXE)

trace:	debug
	valgrind --leak-check=yes --track-origins=yes ./$(EXE)